### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "abc123000@test.ru",
  "password": "qwert"
}

### Sing in
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "abc123000@test.ru",
  "password": "qwert"
}

### Get currently singed user
GET http://localhost:3000/auth/whoami

### Sing out
POST http://localhost:3000/auth/singout

### Find a particular user with a given ID
GET http://localhost:3000/auth/1

### Find all users with a given email
GET http://localhost:3000/auth/?email=abc@test.ru

### Delete a user with a given ID
DELETE http://localhost:3000/auth/2

### Update a user
PATCH http://localhost:3000/auth/1
content-type: application/json

{
  "email": "bbb@test.ru",
  "password": "wsxcde"
}